import Layout from "@/components/Layout/Layout";
import "@/styles/globals.css";
import Head from "next/head";
export default function App({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        <title>Portafolio Luis Rangel</title>
        <meta name="description" content="Generated by Luis Rangel" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  );
}
